// This file is adapted from the source code generated by DSWizard 
#pragma once

// 395285CE-F0CB-4EC0-BCAC-69E153B06EE6
DEFINE_GUID(CLSID_Resizer, 0x395285ce, 0xf0cb, 0x4ec0, 0xbc, 0xac, 0x69, 0xe1, 0x53, 0xb0, 0x6e, 0xe6);
// 85D85D2B-77A5-4674-A459-858BCB822DC9
DEFINE_GUID(IID_IResizer, 0x85d85d2b, 0x77a5, 0x4674, 0xa4, 0x59, 0x85, 0x8b, 0xcb, 0x82, 0x2d, 0xc9);

class DECLSPEC_UUID("85D85D2B-77A5-4674-A459-858BCB822DC9") IResizer;
class IResizer : public IUnknown
{
public:
    virtual HRESULT STDMETHODCALLTYPE SetOutput(int x, int y) = 0;
};

class CResizer : public CTransformFilter, public IResizer
{
public:
    DECLARE_IUNKNOWN;
    static CUnknown * WINAPI CreateInstance(LPUNKNOWN punk, HRESULT *phr);

    // Reveals IResizer and ISpecifyPropertyPages
    STDMETHODIMP NonDelegatingQueryInterface(REFIID riid, void ** ppv);

    // Overrriden from CTransformFilter base class
    HRESULT Transform(IMediaSample *pIn, IMediaSample *pOut);
    HRESULT CheckInputType(const CMediaType *mtIn);
    HRESULT CheckTransform(const CMediaType *mtIn, const CMediaType *mtOut);
    HRESULT DecideBufferSize(IMemAllocator *pAlloc, ALLOCATOR_PROPERTIES *pProperties);
    HRESULT GetMediaType(int iPosition, CMediaType *pMediaType);

    // Implementation of  the custom IResizer interface
    HRESULT STDMETHODCALLTYPE SetOutput(int x, int y);

private:

    CCritSec m_ResizerLock;
    int m_inX, m_inY, m_outX, m_outY;
    int m_bytesPerPixel;
    ULONG m_iSrcScanLine[1024];
    ULONG m_iSrcPixelOffset[768];
    BOOL m_bMakeTables;

    CResizer(TCHAR *tszName, LPUNKNOWN punk, HRESULT *phr);
	~CResizer();

    BOOL CanPerformTransform(const CMediaType *pMediaType) const;
    void MakeScaleTables();
    void ScaleBuf(BYTE *in, BYTE* out);

};

